# Generated by Django 2.2.3 on 2019-08-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20190825_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(default='Gleb + Masha = <3', max_length=8),
        ),
    ]
