# Generated by Django 2.2.6 on 2020-01-10 23:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20190825_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available_tests',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='finished_tests',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
