# Generated by Django 2.2.6 on 2020-04-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20200424_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
