# Generated by Django 2.2.6 on 2020-04-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_auto_20200425_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
