# Generated by Django 2.0.7 on 2019-05-28 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_word', models.CharField(max_length=100)),
                ('hint', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionWithAnswer',
            fields=[
                ('question_text', models.CharField(max_length=300)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%d/%H/%M/%S/')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%H/%M/%S/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_answer', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Question_with_answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionWithVariants',
            fields=[
                ('question_text', models.CharField(max_length=300)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%d/%H/%M/%S/')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/%H/%M/%S/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_variants', models.CharField(max_length=1000)),
                ('question_with_one_answer', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'Question_with_variants',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test_result', models.CharField(blank=True, max_length=100)),
                ('second_test_result', models.CharField(blank=True, max_length=100)),
                ('third_test_result', models.CharField(blank=True, max_length=100)),
                ('fourth_test_result', models.CharField(blank=True, max_length=100)),
                ('fifth_test_result', models.CharField(blank=True, max_length=100)),
                ('six_test_result', models.CharField(blank=True, max_length=100)),
                ('seventh_test_result', models.CharField(blank=True, max_length=100)),
                ('eighth_test_result', models.CharField(blank=True, max_length=100)),
                ('ninth_test_result', models.CharField(blank=True, max_length=100)),
                ('tenth_test_result', models.CharField(blank=True, max_length=100)),
                ('eleventh_test_result', models.CharField(blank=True, max_length=100)),
                ('twelfth_test_result', models.CharField(blank=True, max_length=100)),
                ('thirteenth_test_result', models.CharField(blank=True, max_length=100)),
                ('fourteenth_test_result', models.CharField(blank=True, max_length=100)),
                ('fifteenth_test_result', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_lesson_number', models.IntegerField()),
                ('test_title', models.CharField(max_length=100)),
                ('test_timer', models.IntegerField(blank=True, default=0)),
                ('test_publication_date', models.DateField()),
                ('test_description', models.TextField(blank=True, max_length=2000)),
                ('test_author', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='UsersAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(default=1)),
                ('question_text', models.CharField(max_length=300)),
                ('user_answer', models.CharField(max_length=1000000, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Test'),
        ),
        migrations.AddField(
            model_name='results',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionwithvariants',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Test'),
        ),
        migrations.AddField(
            model_name='questionwithanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Test'),
        ),
    ]
