# Generated by Django 2.2.6 on 2020-04-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='eighth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='eleventh_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='fifteenth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='fifth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='first_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='fourteenth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='fourth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='ninth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='second_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='seventh_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='six_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='tenth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='third_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='thirteenth_test_result',
        ),
        migrations.RemoveField(
            model_name='results',
            name='twelfth_test_result',
        ),
        migrations.AlterField(
            model_name='questionwithanswer',
            name='question_text',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='questionwithvariants',
            name='question_text',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersanswers',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.CreateModel(
            name='UserResultTestArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, max_length=400)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('whenWasFinished', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFinalResultArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_result_description', models.TextField(blank=True, null=True)),
                ('lastFinishedTestDate', models.DateTimeField(default=None)),
                ('whenWasCalculated', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
